export default {
  login: 'ShiroWorks',
  id: 40409601,
  node_id: 'MDQ6VXNlcjQwNDA5NjAx',
  avatar_url: 'https://avatars0.githubusercontent.com/u/40409601?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ShiroWorks',
  html_url: 'https://github.com/ShiroWorks',
  followers_url: 'https://api.github.com/users/ShiroWorks/followers',
  following_url:
    'https://api.github.com/users/ShiroWorks/following{/other_user}',
  gists_url: 'https://api.github.com/users/ShiroWorks/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/ShiroWorks/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ShiroWorks/subscriptions',
  organizations_url: 'https://api.github.com/users/ShiroWorks/orgs',
  repos_url: 'https://api.github.com/users/ShiroWorks/repos',
  events_url: 'https://api.github.com/users/ShiroWorks/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/ShiroWorks/received_events',
  type: 'User',
  site_admin: false,
  name: 'Vilmos Szabó',
  company: null,
  blog: '',
  location: 'Hungary',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 71,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2018-06-19T22:36:51Z',
  updated_at: '2020-07-09T13:10:45Z',
};
